"""SQLAlchemy models — re-exported so Alembic autogenerate picks them up."""

from app.models.access_control import RolePermissionOverride
from app.models.audit import AuditLog
from app.models.auth_challenge import AuthOtpChallenge
from app.models.auth_refresh_session import AuthRefreshSession
from app.models.base import Base, SoftDeleteMixin, TenantMixin, TimestampMixin
from app.models.bug_report import (
    BugReport,
    BugReportAttachment,
    BugReportInboxRead,
    BugReportPublicReply,
)
from app.models.client_diagnostic import ClientDiagnosticEvent
from app.models.client_update import AndroidRelease, ClientInstallation, ClientUpdateEvent
from app.models.customer import (
    Customer,
    OrderLoyaltySettlement,
    PointsRedemption,
    RefundLoyaltyAdjustment,
)
from app.models.events import Event, EventTicket
from app.models.finance import (
    Account,
    Asset,
    CapitalEntry,
    Expense,
    ExpenseCategory,
    JournalEntry,
    JournalLine,
    ManualCollection,
    Partner,
    SupplierPayment,
    TipPayout,
)
from app.models.gaming import (
    GamingBooking,
    GamingPackage,
    GamingSession,
    GamingSessionAddon,
    GamingSessionExtension,
    Station,
    Tournament,
)
from app.models.idempotency_key import IdempotencyKey
from app.models.india import (
    GstRateSlab,
    HsnCode,
    InvoiceCounter,
    KeralaPTSlab,
    SacCode,
    StateCode,
)
from app.models.inventory import (
    GRN,
    Batch,
    GRNLine,
    Ingredient,
    PurchaseOrder,
    PurchaseOrderLine,
    Recipe,
    RecipeLine,
    StockMovement,
    Supplier,
)
from app.models.membership import (
    CustomerMembership,
    MembershipBenefitReservation,
    MembershipCustomerSpendApplication,
    MembershipEvidenceReconciliation,
    MembershipPayment,
    MembershipPaymentAttemptResolution,
    MembershipPaymentCashCollection,
    MembershipPaymentCompletion,
    MembershipPaymentProviderAction,
    MembershipPaymentRequest,
    MembershipPaymentRequestResolution,
    MembershipRefund,
    MembershipRefundAttemptRecovery,
    MembershipRefundAttemptResolution,
    MembershipRefundCashHandoff,
    MembershipRefundCompletion,
    MembershipRefundProviderAction,
    MembershipRefundResolution,
    MembershipRefundSettlement,
    MembershipTier,
)
from app.models.menu import (
    MenuCategory,
    MenuItem,
    MenuModifier,
    MenuModifierGroup,
    MenuVariant,
)
from app.models.ocr import OcrExtraction, OcrUpload, OcrVerification
from app.models.pos import (
    CustomerSpendReconciliation,
    Order,
    OrderCheckoutClaim,
    OrderLine,
    Payment,
    PosRefundCashHandoff,
    PosRefundCashHandoffCompletion,
    PosRefundEvidenceReconciliation,
    PosRefundProviderPayoutStart,
    PosRefundProviderSettlement,
    PosRefundRequest,
    PosRefundWithdrawal,
    Refund,
    Shift,
)
from app.models.tables import Floor, Reservation, Table
from app.models.tenant import Branch, Company, Terminal
from app.models.user import Attendance, PayrollEntry, Role, User, UserRole

__all__ = [
    "Account",
    "AndroidRelease",
    "Asset",
    "Attendance",
    "AuditLog",
    "AuthOtpChallenge",
    "AuthRefreshSession",
    "Base",
    "Batch",
    "Branch",
    "BugReport",
    "BugReportAttachment",
    "BugReportInboxRead",
    "BugReportPublicReply",
    "CapitalEntry",
    "Company",
    "Customer",
    "CustomerSpendReconciliation",
    "ClientInstallation",
    "ClientDiagnosticEvent",
    "ClientUpdateEvent",
    "CustomerMembership",
    "Event",
    "EventTicket",
    "Expense",
    "ExpenseCategory",
    "Floor",
    "GamingBooking",
    "GamingPackage",
    "GamingSession",
    "GamingSessionAddon",
    "GamingSessionExtension",
    "GRN",
    "GRNLine",
    "GstRateSlab",
    "HsnCode",
    "IdempotencyKey",
    "Ingredient",
    "InvoiceCounter",
    "KeralaPTSlab",
    "JournalEntry",
    "JournalLine",
    "MembershipTier",
    "MembershipBenefitReservation",
    "MembershipCustomerSpendApplication",
    "MembershipEvidenceReconciliation",
    "MembershipPayment",
    "MembershipPaymentCashCollection",
    "MembershipPaymentCompletion",
    "MembershipPaymentProviderAction",
    "MembershipPaymentAttemptResolution",
    "MembershipPaymentRequest",
    "MembershipPaymentRequestResolution",
    "MembershipRefund",
    "MembershipRefundAttemptRecovery",
    "MembershipRefundAttemptResolution",
    "MembershipRefundCashHandoff",
    "MembershipRefundCompletion",
    "MembershipRefundProviderAction",
    "MembershipRefundResolution",
    "MembershipRefundSettlement",
    "ManualCollection",
    "MenuCategory",
    "MenuItem",
    "MenuModifier",
    "MenuModifierGroup",
    "MenuVariant",
    "OcrExtraction",
    "OcrUpload",
    "OcrVerification",
    "Order",
    "OrderCheckoutClaim",
    "OrderLoyaltySettlement",
    "OrderLine",
    "Partner",
    "Payment",
    "PayrollEntry",
    "PointsRedemption",
    "PosRefundCashHandoff",
    "PosRefundCashHandoffCompletion",
    "PosRefundEvidenceReconciliation",
    "PosRefundProviderPayoutStart",
    "PosRefundProviderSettlement",
    "PosRefundRequest",
    "PosRefundWithdrawal",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "Recipe",
    "RecipeLine",
    "Refund",
    "RefundLoyaltyAdjustment",
    "Reservation",
    "Role",
    "RolePermissionOverride",
    "SacCode",
    "Shift",
    "SoftDeleteMixin",
    "StateCode",
    "Station",
    "StockMovement",
    "Supplier",
    "SupplierPayment",
    "Table",
    "TenantMixin",
    "Terminal",
    "TimestampMixin",
    "TipPayout",
    "Tournament",
    "User",
    "UserRole",
]
