package cloud.dcompany.erp.core.sync

import cloud.dcompany.erp.core.db.MembershipPaymentTaskCacheEntity
import cloud.dcompany.erp.core.db.MembershipRefundAttemptCacheEntity
import cloud.dcompany.erp.core.db.MembershipRefundTaskCacheEntity
import cloud.dcompany.erp.ui.screens.memberships.MembershipRefundAttemptRecovery
import cloud.dcompany.erp.ui.screens.memberships.MembershipRefundTask
import cloud.dcompany.erp.ui.screens.memberships.MembershipPaymentTask

internal fun MembershipPaymentTask.toCache(
    branchId: String,
    terminalId: String,
    fetchedAtMillis: Long,
): MembershipPaymentTaskCacheEntity = MembershipPaymentTaskCacheEntity(
    id = id,
    branchId = branchId,
    terminalId = terminalId,
    customerId = customerId,
    tierId = tierId,
    shiftId = shiftId,
    billingCycle = billingCycle,
    paidVia = paidVia,
    amountMinor = amountMinor,
    customerName = customerName,
    customerPhone = customerPhone,
    tierCode = tierCode,
    tierName = tierName,
    status = status,
    acceptedAt = acceptedAt,
    preparedBy = preparedBy,
    preparedByName = preparedByName,
    collectionStartedAt = collectionStartedAt,
    valueCompletedAt = valueCompletedAt,
    valueCompletedBy = valueCompletedBy,
    valueCompletedByName = valueCompletedByName,
    actionStartedBy = actionStartedBy,
    actionStartedByName = actionStartedByName,
    actionKind = actionKind,
    settledAt = settledAt,
    settledBy = settledBy,
    settledByName = settledByName,
    membershipId = membershipId,
    paymentId = paymentId,
    receiptNo = receiptNo,
    externalReference = externalReference,
    evidenceOccurredAt = evidenceOccurredAt,
    evidenceTimeUntrusted = evidenceTimeUntrusted,
    providerEvidenceReconciled = providerEvidenceReconciled,
    customerSpendReconciled = customerSpendReconciled,
    resolution = resolution,
    resolvedAt = resolvedAt,
    resolvedBy = resolvedBy,
    resolvedByName = resolvedByName,
    actionStateVerified = actionStateVerified,
    providerVerificationStatus = providerVerificationStatus,
    providerVerificationReference = providerVerificationReference,
    providerCheckedAt = providerCheckedAt,
    cashReturnConfirmed = cashReturnConfirmed,
    actionTakeoverConfirmed = actionTakeoverConfirmed,
    actionTakeoverReason = actionTakeoverReason,
    clientActionId = clientActionId,
    fetchedAtMillis = fetchedAtMillis,
)

internal fun MembershipRefundTask.toCache(
    branchId: String,
    terminalId: String,
    fetchedAtMillis: Long,
): MembershipRefundTaskCacheEntity = MembershipRefundTaskCacheEntity(
    id = id,
    branchId = branchId,
    terminalId = terminalId,
    membershipId = membershipId,
    paymentId = paymentId,
    shiftId = shiftId,
    method = method,
    amountMinor = amountMinor,
    acceptedAt = acceptedAt,
    status = status,
    handoffStartedAt = handoffStartedAt,
    payoutCompletedAt = payoutCompletedAt,
    payoutCompletedBy = payoutCompletedBy,
    payoutCompletedByName = payoutCompletedByName,
    acceptedBy = acceptedBy,
    acceptedByName = acceptedByName,
    actionStartedBy = actionStartedBy,
    actionStartedByName = actionStartedByName,
    actionKind = actionKind,
    settledAt = settledAt,
    settledBy = settledBy,
    settledByName = settledByName,
    reason = reason,
    externalReference = externalReference,
    receiptNo = receiptNo,
    entitlementRestored = entitlementRestored,
    customerId = customerId,
    customerName = customerName,
    customerPhone = customerPhone,
    tierName = tierName,
    originalPaymentReceiptNo = originalPaymentReceiptNo,
    resolution = resolution,
    resolutionReason = resolutionReason,
    resolvedAt = resolvedAt,
    resolvedBy = resolvedBy,
    resolvedByName = resolvedByName,
    evidenceOccurredAt = evidenceOccurredAt,
    evidenceTimeUntrusted = evidenceTimeUntrusted,
    providerEvidenceReconciled = providerEvidenceReconciled,
    customerSpendReconciled = customerSpendReconciled,
    actionStateVerified = actionStateVerified,
    providerVerificationStatus = providerVerificationStatus,
    providerVerificationReference = providerVerificationReference,
    providerCheckedAt = providerCheckedAt,
    cashReturnConfirmed = cashReturnConfirmed,
    actionTakeoverConfirmed = actionTakeoverConfirmed,
    actionTakeoverReason = actionTakeoverReason,
    fetchedAtMillis = fetchedAtMillis,
)

internal fun MembershipRefundAttemptRecovery.toCache(
    branchId: String,
    terminalId: String,
    fetchedAtMillis: Long,
): MembershipRefundAttemptCacheEntity = MembershipRefundAttemptCacheEntity(
    id = id,
    branchId = branchId,
    terminalId = terminalId,
    originalClientActionId = originalClientActionId,
    customerId = customerId,
    membershipId = membershipId,
    paymentId = paymentId,
    sourceShiftId = sourceShiftId,
    expectedAmountMinor = expectedAmountMinor,
    paidVia = paidVia,
    capturedAt = capturedAt,
    capturedTimeUntrusted = capturedTimeUntrusted,
    registeredAt = registeredAt,
    registeredBy = registeredBy,
    registeredByName = registeredByName,
    status = status,
    resolutionId = resolutionId,
    fetchedAtMillis = fetchedAtMillis,
)
