package cloud.dcompany.erp.core.db

import androidx.room.testing.MigrationTestHelper
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Real migrations against real schema history, not a guess. `ErpDatabase`
 * forbids destructive fallback because it holds captured sales and shift
 * state that exist nowhere else until they sync — a migration that's wrong
 * about column names or a `NOT NULL` default isn't a lint warning here, it's
 * a hard crash for every tablet already in the field the moment it updates.
 *
 * Schema snapshots live in `androidTest/assets/schemas/`, generated by Room
 * itself (`ksp { arg("room.schemaLocation", ...) }` in build.gradle.kts),
 * never hand-written — a hand-authored identityHash would defeat the point
 * of this test.
 */
@RunWith(AndroidJUnit4::class)
class MigrationTest {

    private val dbName = "migration-test"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        ErpDatabase::class.java,
        emptyList(),
    )

    @Test
    fun migrate1To2_preservesExistingDataAndAddsLocalShifts() {
        // Seed a v1 database with real rows — the migration is additive-only
        // (CREATE TABLE, no ALTER against menu_items/local_orders/etc), but
        // the whole point of testing it is not trusting that by inspection.
        helper.createDatabase(dbName, 1).apply {
            execSQL(
                "INSERT INTO menu_categories (id, name, sortOrder) VALUES ('cat-1', 'Drinks', 0)",
            )
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO local_orders (localId, shiftId, type, estimateMinor, paymentMethod, " +
                    "tenderedMinor, tipMinor, createdAtMillis, syncState) " +
                    "VALUES ('order-1', 'shift-1', 'dine_in', 12000, 'cash', 12000, 0, 1000, 'pending')",
            )
            close()
        }

        // MIGRATION_1_2 only adds local_shifts — validated against the real,
        // Room-generated v2 schema (schemas/.../2.json), not a hand check.
        val migrated = helper.runMigrationsAndValidate(dbName, 2, true, MIGRATION_1_2)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT localId, syncState FROM local_orders WHERE localId = 'order-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_orders row lost across the migration — this is real captured revenue" }
            assert(cursor.getString(1) == "pending")
        }
        migrated.query("SELECT COUNT(*) FROM local_shifts").use { cursor ->
            cursor.moveToFirst()
            assert(cursor.getInt(0) == 0) { "local_shifts should exist and start empty" }
        }
        migrated.close()
    }

    @Test
    fun migrate2To3_preservesExistingDataAndAddsPhase2Tables() {
        // v2 already has local_shifts (from MIGRATION_1_2) — seed one real
        // open shift plus the same v1 rows, so this test also proves the
        // Phase 2 migration doesn't disturb Phase 1's table.
        helper.createDatabase(dbName, 2).apply {
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO local_shifts (localId, openingFloatMinor, openedAtMillis, state) " +
                    "VALUES ('shift-1', 100000, 1000, 'open_synced')",
            )
            close()
        }

        // MIGRATION_2_3 adds the 8 Phase 2 tables (gaming/kitchen/tables) in
        // one pass — validated against the real, Room-generated v3 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 3, true, MIGRATION_2_3)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT localId, state FROM local_shifts WHERE localId = 'shift-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_shifts row lost across the migration" }
            assert(cursor.getString(1) == "open_synced")
        }
        for (table in listOf(
            "gaming_stations", "gaming_session_cache", "local_gaming_sessions",
            "kitchen_order_cache", "local_kitchen_advances",
            "cafe_floors", "cafe_tables", "local_table_orders",
        )) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate3To4_preservesExistingDataAndAddsRefundTables() {
        // v3 already has a Phase 2 table (gaming_stations) — seed one row
        // there plus a v1 row, so this test also proves the Phase 3
        // migration doesn't disturb earlier phases' tables.
        helper.createDatabase(dbName, 3).apply {
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO gaming_stations (id, code, name, type, ratePerHourMinor, isActive) " +
                    "VALUES ('station-1', 'PS5-01', 'PS5 Station 1', 'ps5', 15000, 1)",
            )
            close()
        }

        // MIGRATION_3_4 adds the 2 Phase 3 tables (Refunds) — validated
        // against the real, Room-generated v4 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 4, true, MIGRATION_3_4)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT id, name FROM gaming_stations WHERE id = 'station-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "gaming_stations row lost across the migration" }
            assert(cursor.getString(1) == "PS5 Station 1")
        }
        for (table in listOf("refund_order_cache", "local_refunds")) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate4To5_preservesExistingDataAndAddsReportSnapshots() {
        // v4 already has a Phase 3 table (local_refunds) — seed one row there
        // plus a v1 row, so this test also proves the Phase 5 migration
        // doesn't disturb earlier phases' tables.
        helper.createDatabase(dbName, 4).apply {
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO local_refunds (localId, orderId, reasonCode, amountMinor, createdAtMillis, state) " +
                    "VALUES ('refund-1', 'order-1', 'other', 4300, 1000, 'synced')",
            )
            close()
        }

        // MIGRATION_4_5 adds the one Phase 5 table (report_snapshots) —
        // validated against the real, Room-generated v5 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 5, true, MIGRATION_4_5)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT localId, state FROM local_refunds WHERE localId = 'refund-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_refunds row lost across the migration" }
            assert(cursor.getString(1) == "synced")
        }
        migrated.query("SELECT COUNT(*) FROM report_snapshots").use { cursor ->
            cursor.moveToFirst()
            assert(cursor.getInt(0) == 0) { "report_snapshots should exist and start empty" }
        }
        migrated.close()
    }

    @Test
    fun migrate5To6_preservesExistingDataAndAddsCustomerTables() {
        // v5 already has a Phase 5 table (report_snapshots) — seed a row
        // there plus a v1 row, so this test also proves the Phase 6
        // migration doesn't disturb earlier phases' tables.
        helper.createDatabase(dbName, 5).apply {
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO report_snapshots (`key`, jsonBody, fetchedAtMillis) " +
                    "VALUES ('daily:2026-08-19', '{}', 1000)",
            )
            close()
        }

        // MIGRATION_5_6 adds the two Phase 6 tables (customer_cache,
        // local_customers) — validated against the real, Room-generated v6
        // schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 6, true, MIGRATION_5_6)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT `key`, jsonBody FROM report_snapshots WHERE `key` = 'daily:2026-08-19'").use { cursor ->
            assert(cursor.moveToFirst()) { "report_snapshots row lost across the migration" }
            assert(cursor.getString(1) == "{}")
        }
        for (table in listOf("customer_cache", "local_customers")) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate6To7_preservesExistingDataAndWidensMenuItemsAndAddsMenuOutboxTables() {
        // v6 already has a Phase 6 table (local_customers) — seed a row
        // there plus a v1 menu_items row (using v6's narrower column set,
        // since `type`/`hsnCode`/`priceIncludesTax`/`description` don't
        // exist until this migration adds them), so this test also proves
        // the Phase 7 migration doesn't disturb earlier phases' tables.
        helper.createDatabase(dbName, 6).apply {
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO local_customers (localId, phone, createdAtMillis, state, version) " +
                    "VALUES ('cust-1', '9999900001', 1000, 'synced', 0)",
            )
            close()
        }

        // MIGRATION_6_7 widens menu_items (type/hsnCode/priceIncludesTax/
        // description) and adds the two Phase 7 outbox tables
        // (local_menu_categories, local_menu_items) — validated against the
        // real, Room-generated v7 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 7, true, MIGRATION_6_7)

        migrated.query(
            "SELECT name, type, hsnCode, priceIncludesTax, description FROM menu_items WHERE id = 'item-1'",
        ).use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(0) == "Cold Coffee")
            assert(cursor.getString(1) == "") { "new NOT NULL `type` column should default to ''" }
            assert(cursor.isNull(2)) { "new nullable `hsnCode` column should default to NULL" }
            assert(cursor.getInt(3) == 1) { "new NOT NULL `priceIncludesTax` column should default to true" }
            assert(cursor.isNull(4)) { "new nullable `description` column should default to NULL" }
        }
        migrated.query("SELECT localId, state FROM local_customers WHERE localId = 'cust-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_customers row lost across the migration" }
            assert(cursor.getString(1) == "synced")
        }
        for (table in listOf("local_menu_categories", "local_menu_items")) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate7To8_preservesExistingDataAndAddsStaffAndAttendanceTables() {
        // Same "oldest table survives" canary the rest of this file uses —
        // a v1 menu_items row (v7's already-widened column set, since
        // MIGRATION_6_7 already ran by this point) plus a Phase 7 table
        // (local_menu_categories), to prove this migration disturbs neither
        // the original table nor the immediately-preceding phase's.
        helper.createDatabase(dbName, 7).apply {
            execSQL(
                "INSERT INTO menu_items " +
                    "(id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable, type, hsnCode, priceIncludesTax, description) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1, 'drink', NULL, 1, NULL)",
            )
            execSQL(
                "INSERT INTO local_menu_categories (localId, name, createdAtMillis, state, version) " +
                    "VALUES ('cat-1', 'Snacks', 1000, 'synced', 0)",
            )
            close()
        }

        // MIGRATION_7_8 adds the three new Phase 8 tables (staff_cache,
        // local_staff, on_shift_cache) — validated against the real,
        // Room-generated v8 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 8, true, MIGRATION_7_8)

        migrated.query("SELECT name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(0) == "Cold Coffee")
        }
        migrated.query("SELECT localId, name, state FROM local_menu_categories WHERE localId = 'cat-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_menu_categories row lost across the migration" }
            assert(cursor.getString(1) == "Snacks")
            assert(cursor.getString(2) == "synced")
        }
        for (table in listOf("staff_cache", "local_staff", "on_shift_cache")) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate8To9_preservesExistingDataAndAddsInventoryTables() {
        // Same "oldest table survives" canary — a v1 menu_items row plus a
        // Phase 8 table (local_staff) — to prove this migration disturbs
        // neither the original table nor the immediately-preceding phase's.
        helper.createDatabase(dbName, 8).apply {
            execSQL(
                "INSERT INTO menu_items " +
                    "(id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable, type, hsnCode, priceIncludesTax, description) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1, 'drink', NULL, 1, NULL)",
            )
            execSQL(
                "INSERT INTO local_staff " +
                    "(localId, serverId, name, phone, status, roleCode, pendingDelete, createdAtMillis, state, lastError, version) " +
                    "VALUES ('staff-1', 'server-staff-1', 'Rafi', NULL, NULL, NULL, 0, 1000, 'synced', NULL, 0)",
            )
            close()
        }

        // MIGRATION_8_9 adds the eight new Phase 9 tables (ingredient_cache,
        // local_ingredients, supplier_cache, local_suppliers, batch_cache,
        // local_grns, local_grn_lines, local_adjustments) — validated against
        // the real, Room-generated v9 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 9, true, MIGRATION_8_9)

        migrated.query("SELECT name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(0) == "Cold Coffee")
        }
        migrated.query("SELECT localId, name, state FROM local_staff WHERE localId = 'staff-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_staff row lost across the migration" }
            assert(cursor.getString(1) == "Rafi")
            assert(cursor.getString(2) == "synced")
        }
        for (table in listOf(
            "ingredient_cache", "local_ingredients", "supplier_cache", "local_suppliers",
            "batch_cache", "local_grns", "local_grn_lines", "local_adjustments",
        )) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate9To10_preservesExistingDataAndAddsFinanceTables() {
        // Same "oldest table survives" canary — a v1 menu_items row plus a
        // Phase 9 table (local_ingredients) — to prove this migration
        // disturbs neither the original table nor the immediately-preceding
        // phase's.
        helper.createDatabase(dbName, 9).apply {
            execSQL(
                "INSERT INTO menu_items " +
                    "(id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable, type, hsnCode, priceIncludesTax, description) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1, 'drink', NULL, 1, NULL)",
            )
            execSQL(
                "INSERT INTO local_ingredients " +
                    "(localId, serverId, sku, name, baseUnit, reorderThreshold, reorderQty, pendingDelete, createdAtMillis, state, lastError, version) " +
                    "VALUES ('ing-1', 'server-ing-1', 'COFFEE-BEAN', 'Coffee', 'g', 500, 1000, 0, 1000, 'synced', NULL, 0)",
            )
            close()
        }

        // MIGRATION_9_10 adds the six new Phase 10 tables (expense_cache,
        // local_expenses, asset_cache, local_assets, capital_entry_cache,
        // local_capital_entries) — validated against the real, Room-generated
        // v10 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 10, true, MIGRATION_9_10)

        migrated.query("SELECT name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(0) == "Cold Coffee")
        }
        migrated.query("SELECT localId, name, state FROM local_ingredients WHERE localId = 'ing-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_ingredients row lost across the migration" }
            assert(cursor.getString(1) == "Coffee")
            assert(cursor.getString(2) == "synced")
        }
        for (table in listOf(
            "expense_cache", "local_expenses", "asset_cache", "local_assets",
            "capital_entry_cache", "local_capital_entries",
        )) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate10To11_preservesExistingDataAndAddsEventTables() {
        // Same "oldest table survives" canary — a v1 menu_items row plus a
        // Phase 10 table (local_expenses) — to prove this migration disturbs
        // neither the original table nor the immediately-preceding phase's.
        helper.createDatabase(dbName, 10).apply {
            execSQL(
                "INSERT INTO menu_items " +
                    "(id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable, type, hsnCode, priceIncludesTax, description) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1, 'drink', NULL, 1, NULL)",
            )
            execSQL(
                "INSERT INTO local_expenses " +
                    "(localId, branchId, categoryId, supplierId, amountMinor, paidVia, paidAt, vendorName, invoiceNo, note, createdAtMillis, syncState, lastError) " +
                    "VALUES ('exp-1', 'branch-1', 'cat-1', NULL, 45000, 'cash', '2026-08-22T10:00:00Z', NULL, NULL, NULL, 1000, 'synced', NULL)",
            )
            close()
        }

        // MIGRATION_10_11 adds the four new Phase 11 tables (event_cache,
        // event_ticket_cache, local_ticket_sales, local_check_ins) —
        // validated against the real, Room-generated v11 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 11, true, MIGRATION_10_11)

        migrated.query("SELECT name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(0) == "Cold Coffee")
        }
        migrated.query("SELECT localId, amountMinor, syncState FROM local_expenses WHERE localId = 'exp-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_expenses row lost across the migration" }
            assert(cursor.getLong(1) == 45000L)
            assert(cursor.getString(2) == "synced")
        }
        for (table in listOf(
            "event_cache", "event_ticket_cache", "local_ticket_sales", "local_check_ins",
        )) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate11To12_preservesExistingDataAndAddsMembershipTables() {
        // Same "oldest table survives" canary — a v1 menu_items row plus a
        // Phase 11 table (local_ticket_sales) — to prove this migration
        // disturbs neither the original table nor the immediately-preceding
        // phase's.
        helper.createDatabase(dbName, 11).apply {
            execSQL(
                "INSERT INTO menu_items " +
                    "(id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable, type, hsnCode, priceIncludesTax, description) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1, 'drink', NULL, 1, NULL)",
            )
            execSQL(
                "INSERT INTO local_ticket_sales " +
                    "(localId, eventId, customerName, customerPhone, seat, qty, note, createdAtMillis, syncState, lastError) " +
                    "VALUES ('sale-1', 'event-1', 'Rahul', NULL, NULL, 2, NULL, 1000, 'synced', NULL)",
            )
            close()
        }

        // MIGRATION_11_12 adds the four new Phase 12 tables (membership_tier_cache,
        // customer_membership_cache, local_subscriptions, local_membership_cancellations)
        // — validated against the real, Room-generated v12 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 12, true, MIGRATION_11_12)

        migrated.query("SELECT name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(0) == "Cold Coffee")
        }
        migrated.query("SELECT localId, customerName, syncState FROM local_ticket_sales WHERE localId = 'sale-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_ticket_sales row lost across the migration" }
            assert(cursor.getString(1) == "Rahul")
            assert(cursor.getString(2) == "synced")
        }
        for (table in listOf(
            "membership_tier_cache", "customer_membership_cache",
            "local_subscriptions", "local_membership_cancellations",
        )) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }
}
