package cloud.dcompany.erp.core.db

import androidx.room.testing.MigrationTestHelper
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Real migrations against real schema history, not a guess. `ErpDatabase`
 * forbids destructive fallback because it holds captured sales and shift
 * state that exist nowhere else until they sync — a migration that's wrong
 * about column names or a `NOT NULL` default isn't a lint warning here, it's
 * a hard crash for every tablet already in the field the moment it updates.
 *
 * Schema snapshots live in `androidTest/assets/schemas/`, generated by Room
 * itself (`ksp { arg("room.schemaLocation", ...) }` in build.gradle.kts),
 * never hand-written — a hand-authored identityHash would defeat the point
 * of this test.
 */
@RunWith(AndroidJUnit4::class)
class MigrationTest {

    private val dbName = "migration-test"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        ErpDatabase::class.java,
        emptyList(),
    )

    @Test
    fun migrate1To2_preservesExistingDataAndAddsLocalShifts() {
        // Seed a v1 database with real rows — the migration is additive-only
        // (CREATE TABLE, no ALTER against menu_items/local_orders/etc), but
        // the whole point of testing it is not trusting that by inspection.
        helper.createDatabase(dbName, 1).apply {
            execSQL(
                "INSERT INTO menu_categories (id, name, sortOrder) VALUES ('cat-1', 'Drinks', 0)",
            )
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO local_orders (localId, shiftId, type, estimateMinor, paymentMethod, " +
                    "tenderedMinor, tipMinor, createdAtMillis, syncState) " +
                    "VALUES ('order-1', 'shift-1', 'dine_in', 12000, 'cash', 12000, 0, 1000, 'pending')",
            )
            close()
        }

        // MIGRATION_1_2 only adds local_shifts — validated against the real,
        // Room-generated v2 schema (schemas/.../2.json), not a hand check.
        val migrated = helper.runMigrationsAndValidate(dbName, 2, true, MIGRATION_1_2)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT localId, syncState FROM local_orders WHERE localId = 'order-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_orders row lost across the migration — this is real captured revenue" }
            assert(cursor.getString(1) == "pending")
        }
        migrated.query("SELECT COUNT(*) FROM local_shifts").use { cursor ->
            cursor.moveToFirst()
            assert(cursor.getInt(0) == 0) { "local_shifts should exist and start empty" }
        }
        migrated.close()
    }

    @Test
    fun migrate2To3_preservesExistingDataAndAddsPhase2Tables() {
        // v2 already has local_shifts (from MIGRATION_1_2) — seed one real
        // open shift plus the same v1 rows, so this test also proves the
        // Phase 2 migration doesn't disturb Phase 1's table.
        helper.createDatabase(dbName, 2).apply {
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO local_shifts (localId, openingFloatMinor, openedAtMillis, state) " +
                    "VALUES ('shift-1', 100000, 1000, 'open_synced')",
            )
            close()
        }

        // MIGRATION_2_3 adds the 8 Phase 2 tables (gaming/kitchen/tables) in
        // one pass — validated against the real, Room-generated v3 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 3, true, MIGRATION_2_3)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT localId, state FROM local_shifts WHERE localId = 'shift-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_shifts row lost across the migration" }
            assert(cursor.getString(1) == "open_synced")
        }
        for (table in listOf(
            "gaming_stations", "gaming_session_cache", "local_gaming_sessions",
            "kitchen_order_cache", "local_kitchen_advances",
            "cafe_floors", "cafe_tables", "local_table_orders",
        )) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate3To4_preservesExistingDataAndAddsRefundTables() {
        // v3 already has a Phase 2 table (gaming_stations) — seed one row
        // there plus a v1 row, so this test also proves the Phase 3
        // migration doesn't disturb earlier phases' tables.
        helper.createDatabase(dbName, 3).apply {
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO gaming_stations (id, code, name, type, ratePerHourMinor, isActive) " +
                    "VALUES ('station-1', 'PS5-01', 'PS5 Station 1', 'ps5', 15000, 1)",
            )
            close()
        }

        // MIGRATION_3_4 adds the 2 Phase 3 tables (Refunds) — validated
        // against the real, Room-generated v4 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 4, true, MIGRATION_3_4)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT id, name FROM gaming_stations WHERE id = 'station-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "gaming_stations row lost across the migration" }
            assert(cursor.getString(1) == "PS5 Station 1")
        }
        for (table in listOf("refund_order_cache", "local_refunds")) {
            migrated.query("SELECT COUNT(*) FROM $table").use { cursor ->
                cursor.moveToFirst()
                assert(cursor.getInt(0) == 0) { "$table should exist and start empty" }
            }
        }
        migrated.close()
    }

    @Test
    fun migrate4To5_preservesExistingDataAndAddsReportSnapshots() {
        // v4 already has a Phase 3 table (local_refunds) — seed one row there
        // plus a v1 row, so this test also proves the Phase 5 migration
        // doesn't disturb earlier phases' tables.
        helper.createDatabase(dbName, 4).apply {
            execSQL(
                "INSERT INTO menu_items (id, categoryId, sku, name, basePriceMinor, taxRate, isAvailable) " +
                    "VALUES ('item-1', 'cat-1', 'SKU1', 'Cold Coffee', 12000, 0.05, 1)",
            )
            execSQL(
                "INSERT INTO local_refunds (localId, orderId, reasonCode, amountMinor, createdAtMillis, state) " +
                    "VALUES ('refund-1', 'order-1', 'other', 4300, 1000, 'synced')",
            )
            close()
        }

        // MIGRATION_4_5 adds the one Phase 5 table (report_snapshots) —
        // validated against the real, Room-generated v5 schema.
        val migrated = helper.runMigrationsAndValidate(dbName, 5, true, MIGRATION_4_5)

        migrated.query("SELECT id, name FROM menu_items WHERE id = 'item-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "menu_items row lost across the migration" }
            assert(cursor.getString(1) == "Cold Coffee")
        }
        migrated.query("SELECT localId, state FROM local_refunds WHERE localId = 'refund-1'").use { cursor ->
            assert(cursor.moveToFirst()) { "local_refunds row lost across the migration" }
            assert(cursor.getString(1) == "synced")
        }
        migrated.query("SELECT COUNT(*) FROM report_snapshots").use { cursor ->
            cursor.moveToFirst()
            assert(cursor.getInt(0) == 0) { "report_snapshots should exist and start empty" }
        }
        migrated.close()
    }
}
